project_custom_field_1_id: # SharePointディレクトリ:
project_custom_field_2_id: # 見積フォルダ:
issue_custom_field_1_id: # お客様名
issue_custom_field_2_id: # 見積フォルダのリンク
issue_custom_field_3_id: # 見積書のリンク
issue_custom_field_4_id: # 見積No.